### ISSUE TITLE
VS Code Settings UI Subfolder is called "Example Configuration" rather than something SUS-specific 

### ISSUE THREAD

**Issue by pbeart** [pc2/sus-lsp#1]
![image](https://github.com/user-attachments/assets/7e082ee8-b8fb-4770-8f05-e567b8dadea5)

**Comment by VonTum** [comment]
Also we should replace sus_lsp.some_setting with a nicer graphical name

![image](https://github.com/user-attachments/assets/a063b885-4619-4318-b321-cfc030189d07)
